### ISSUE TITLE
Check that all required nodes exist for plugin description

### ISSUE THREAD

**Issue by NateWr** [kabaros/pkp-plugin-cli#1]
Aside from the checks on release packages, the following nodes should be required in each plugin:

- One `<name>`.
- One `<homepage>` with a URL that resolves with a `200` http status.
- One `<summary>`.
- One `<description>`.
- One `<maintainer>` with:
  - One `<name>`
  - One `<institution>`
  - One `<email>`

@asmecher Where we specify `locale`, do we require it to be `en_US` or at least one of the nodes be `en_US`?

**Comment by kabaros** [comment]
These should already be enforced as we're running the schema validation at [the first step of the build](https://github.com/kabaros/plugins-registry/blob/master/.travis.yml#L12)

This is the link to the schema http://pkp.sfu.ca/ojs/xml/plugins.xsd

**Comment by NateWr** [comment]
D'oh!
